//...but some pagination logic will  be needed here as well, to get the NEXT photo or the PREVIOUS photo...
//gonna go out on a limb here and say that this iwll be the trickest to implement. wHAT FUN!